# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.13'
steps:
- task: CMake@1
  inputs:
    cmakeArgs: .. -DLLVM_ENABLE_PROJECTS=all -DCMAKE_BUILD_TYPE=Release
- task: CMake@1
  inputs:
    cmakeArgs: .. --build -DCMAKE_INSTALL_PREFIX=$(Build.SourcesDirectory)/install . --target install