# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master
pool:
  vmImage: 'macOS-10.13'
steps:
- task: Bash@3
  inputs:
    targetType: inline
    script: brew install swig
- task: CMake@1
  inputs:
    cmakeArgs: $(Build.SourcesDirectory)/llvm -DLLVM_ENABLE_PROJECTS=all -DCMAKE_BUILD_TYPE=Release
- task: Bash@3
  inputs:
    targetType: inline
    script: mkdir -p $(Build.BinariesDirectory)/install
- task: CMake@1
  inputs:
    cmakeArgs: $(Build.SourcesDirectory)/llvm --build -DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory) . --target install
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'tar'
    tarCompression: 'gz'
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz
    replaceExistingArchive: true
- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'dap-package-llvm'
    vstsFeedPackagePublish: 'dap-llvm'
    packagePublishDescription: '<Package description>'